--- #YAML:1.0
name:               Unix-Groups
version:            0.01
abstract:           Perl to support C<getgroups> and C<setgroups> syscalls
author:
    - Torsten Förtsch <torsten.foertsch@gmx.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
